version: "3"

services:
  node-server:
    build: ./node-server
    container_name: node-server-container
    ports:
      - 3000:3000

  go-server:
    build: ./go-server
    container_name: go-server-container
    ports:
      - 8000:8000

  nginx:
    build: ./nginx
    container_name: nginx-server-gateway
    ports:
      - 80:80
    depends_on:
      - node-server
      - go-server
